=== ParsonsTKO/FolgerMirandaServer/src/DAPImportBundle/Resources/schemas/folger-csv.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {},
    "id": "contentype/csv",
    "title": "Folger CSV",
    "description": "",
    "items": {
      "id" : "/items",
        "properties" : {
        "RemoteUniqueID": {
            "id": "/properties/RemoteUniqueID",
            "type": "string"
        },
        "fileURL" : {
          "id": "/properties/fileURL",
          "type": ["null", "string"]
        },
        "about": {
            "id": "/properties/about",
            "items": {
                "id": "/properties/about/items",
                "properties": {
                    "uri": {
                        "id": "/properties/about/items/properties/uri",
                        "type": ["null", "string"]
                    },
                    "description": {
                        "id": "/properties/about/items/properties/description",
                        "type": ["null", "string"]
                    }
                },
                "type": ["null", "object"]
            },
            "type": ["null", "array"]
        },
        "additionalType": {
            "id": "/properties/additionalType",
            "type": ["null", "string"]
        },
        "alternateName": {
            "id": "/properties/alternateName",
            "type": ["null", "string"]
        },
        "creator": {
            "id": "/properties/creator",
            "properties": {
                "authority": {
                    "id": "/properties/creator/properties/authority",
                    "type": ["null", "string"]
                },
                "familyName": {
                    "id": "/properties/creator/properties/familyName",
                    "type": ["null", "string"]
                },
                "givenName": {
                    "id": "/properties/creator/properties/givenName",
                    "type": ["null", "string"]
                }
            },
            "type": ["null", "object"]
        },
        "dateCreated": {
            "id": "/properties/dateCreated",
            "type": "string"
        },
        "datePublished": {
            "id": "/properties/datePublished",
            "properties": {
                "endDate": {
                    "id": "/properties/datePublished/properties/endDate",
                    "type": ["null", "integer"]
                },
                "startDate": {
                    "id": "/properties/datePublished/properties/startDate",
                    "type": ["null", "integer"]
                }
            },
            "type": "object"
        },
        "description": {
            "id": "/properties/description",
            "type": "string"
        },
        "extent": {
            "id": "/properties/extent",
            "type": ["null", "string"]
        },
        "folgerCallNumber": {
            "id": "/properties/folgerCallNumber",
            "type": ["null", "string"]
        },
        "folgerDimensions": {
            "id": "/properties/folgerDimensions",
            "type": ["null", "string"]
        },
        "folgerProvenance": {
            "id": "/properties/folgerProvenance",
            "type": ["null", "string"]
        },
        "folgerRelatedItems": {
            "id": "/properties/folgerRelatedItems",
            "items": {
                "id": "/properties/folgerRelatedItems/items",
                "properties": {
                    "@id": {
                        "id": "/properties/folgerRelatedItems/items/properties/@id",
                        "type": ["null", "string"]
                    },
                    "folgerRemoteIdentification" : {
                        "id" : "/properties/folgerRelatedItems/items/properties/folgerRemoteIdentification",
                        "type" : "object",
                        "properties" : {
                            "folgerRemoteUniqueID" : {
                                "id" : "/properties/folgerRelatedItems/items/properties/folgerRemoteIdentification/properties/folgerRemoteUniqueID",
                                "type" : "string"
                            },
                            "folgerRemoteSystemID" : {
                                "id" : "/properties/folgerRelatedItems/items/properties/folgerRemoteIdentification/properties/folgerRemoteSystemID",
                                "type" : "string"
                            }
                        }
                    },
                    "folgerRelationshipType" : {
                        "id" : "/properties/folgerRelatedItems/items/properties/folgerRelationshipType",
                        "type" : "string"
                    },
                    "folgerObjectType" : {
                        "id" : "/properties/folgerRelatedItems/items/properties/folgerObjectType",
                        "type" : "string"
                    },
                    "label": {
                        "id": "/properties/folgerRelatedItems/items/properties/label",
                        "type": "string"
                    },
                    "mpso": {
                        "id": "/properties/folgerRelatedItems/items/properties/mpso",
                        "type": "integer"
                    },
                    "description": {
                        "id": "/properties/folgerRelatedItems/items/properties/description",
                        "type": "string"
                    }
                },
                "type": ["null", "object"]
            },
            "type": "array"
        },
        "format": {
            "id": "/properties/format",
            "type": "string"
        },
        "from": {
            "id": "/properties/from",
            "type": ["null", "string"]
        },
        "genre": {
            "id": "/properties/genre",
            "items": {
                "id": "/properties/genre/items",
                "properties": {
                    "search": {
                        "id": "/properties/genre/items/properties/search",
                        "type": "string"
                    },
                    "terms": {
                        "id": "/properties/genre/items/properties/terms",
                        "items": {
                            "id": "/properties/genre/items/properties/terms/items",
                            "type": "string"
                        },
                        "type": "array"
                    },
                    "uri": {
                        "id": "/properties/genre/items/properties/uri",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "type": "array"
        },
        "inLanguage": {
            "id": "/properties/inLanguage",
            "type": "string"
        },
        "isBasedOn": {
            "id": "/properties/isBasedOn",
            "type": ["null", "string"]
        },
        "license": {
            "id": "/properties/license",
            "type": ["null", "string"]
        },
        "locationCreated": {
            "id": "/properties/locationCreated",
            "properties": {
                "addressLocality": {
                    "id": "/properties/locationCreated/properties/addressLocality",
                    "type": ["null", "string"]
                },
                "addressCountry": {
                    "id": "/properties/locationCreated/properties/addressCountry",
                    "type": ["null", "string"]
                }
            },
            "type": "object"
        },
        "MPSO": {
            "id": "/properties/MPSO",
            "type": ["null", "integer"]
        },
        "name": {
            "id": "/properties/name",
            "type": "string"
        },
        "position": {
            "id": "/properties/position",
            "type": ["null", "string"]
        },
        "publisher": {
            "id": "/properties/Publisher",
            "type": ["null", "string"]
        },
        "size": {
            "id": "/properties/Size",
            "type": ["null", "string"]
        },

        "fileStorage" : {
            "id" : "/properties/fileStorage",
            "type" :["null", "string"]
        },
        "contentSize" : {
            "id" : "/properties/contentSize",
            "type" : ["null", "string"]
        },
        "fieldList" : {
            "id" : "/properties/fieldList",
            "items" : {
                "id" : "/properties/fieldList/items",
                "type" : "string"
            },
            "type" : "array"
        },
        "numberOfRows" : {
            "id" : "/properties/numberOfRows",
            "type" : ["null", "integer"]
        }
    },
    "required": [
        "RemoteUniqueID"
    ],
    "type": "object"
},
  "type" : "array"
}

=== ParsonsTKO/FolgerMirandaServer/web/sample-data/json-files/binary-assets/audio-trecento-L-bridge.json
[{
  "RemoteUniqueID": "John Is Testing This",
  "name":  "Florence: Christmas Music of the Trecento AKG_L (Acts 1 & 2) (qwasg)" ,
  "datePublished": {"startDate": 2012, "endDate":2012},
  "dateCreated": "December 14-23,2012",
  "locationCreated" : 
  {
    "@type": "Place",
    "addressLocality": "Washington D.C.",
    "addressCountry": "United States",
    "URI":"http://id.loc.gov/authorities/names/n79018774"
  },
  "description": "DATE OF CONCERTS: December 14-23,2012 TITLE OF PERFORMANCE: FLORENCE: Christmas Music of the Trecento ARTISTS AND INSTRUMENTS: Christa Patton (Harp, Recorder, Bagpipe) Mark Rimple (Lute, Psaltery, Medieval Fiddle) Mary Springles (Medieval Fiddle, Citole) Trios Eos (Vocal Ensemble) Robert Einstein (Medieval Fiddle, Recorder, Lute)",
  "format" : "sound",
  "inLanguage": "eng",
  "genre" :
  [
    {
      "search": "Live sound recordings", 
      "terms": ["Live sound recordings"],
      "uri": "http://id.loc.gov/authorities/genreForms/gf2011026368"
    },
    {
      "search": "Christmas music",
      "terms": ["Christmas music"],
      "uri": "http://id.loc.gov/authorities/genreForms/gf2014026716"
    }
  ],
  "folgerRelatedItems" : [
    {
      "folgerRemoteIdentification" : {
        "folgerRemoteUniqueID" : "http://dapdev.dev/var/folger/storage/trecento/AKG_L_Act_1.wav",
        "folgerRemoteSystemID" : "1"
      },
      "folgerRelationshipType" : "included",
      "folgerObjectType" : "audio"
    },
    {
      "folgerRemoteIdentification" : {
        "folgerRemoteUniqueID" : "http://dapdev.dev/var/folger/storage/trecento/AKG_L_Act_2.wav",
        "folgerRemoteSystemID" : "1"
      },
      "folgerRelationshipType" : "included",
      "folgerObjectType" : "audio"
    }
  ]
}]

=== ParsonsTKO/FolgerMirandaServer/web/sample-data/json-files/binary-assets/csv-sample.json
[{
  "RemoteUniqueID": "http://www.sample-videos.com/csv/Sample-Spreadsheet-10-rows.csv",
  "fileURL": "http://www.sample-videos.com/csv/Sample-Spreadsheet-10-rows.csv",
  "name":  "Sample CSV File" ,
  "datePublished": {"startDate": 2017},
  "dateCreated": "2017",
  "description": "Sample CSV file with 10 rows",
  "format" : "csv",
  "inLanguage": "eng",
  
  "contentSize" : "2k",
  "fieldList" : [
    "product name",
    "person name",
    "integer one",
    "floating point one",
    "second floating point",
    "last number",
    "placename",
    "category",
    "rating"
  ],
  "numberOfRows": 10

}]

=== ParsonsTKO/FolgerMirandaServer/web/sample-data/json-files/audio-example-Florence-Christmas-Music-Trecento.json
[{
  "RemoteUniqueID": "https://parsonstko.teamwork.com/#messages/748875",
  "isBasedOn": "https://parsonstko.teamwork.com/#messages/748875",
  "name":  "Florence: Christmas Music of the Trecento" ,
  "datePublished": {"startDate": 2012, "endDate":2012},
  "dateCreated": "December 14-23,2012",
  "locationCreated" : 
  {
    "@type": "Place",
    "addressLocality": "Washington D.C.",
    "addressCountry": "United States",
    "URI":"http://id.loc.gov/authorities/names/n79018774"
  },
  "description": "DATE OF CONCERTS: December 14-23,2012 TITLE OF PERFORMANCE: FLORENCE: Christmas Music of the Trecento ARTISTS AND INSTRUMENTS: Christa Patton (Harp, Recorder, Bagpipe) Mark Rimple (Lute, Psaltery, Medieval Fiddle) Mary Springles (Medieval Fiddle, Citole) Trios Eos (Vocal Ensemble) Robert Einstein (Medieval Fiddle, Recorder, Lute)",
  "format" : "sound",
  "inLanguage": "eng",
  "genre" :
  [
    {
      "search": "Live sound recordings", 
      "terms": ["Live sound recordings"],
      "uri": "http://id.loc.gov/authorities/genreForms/gf2011026368"
    },
    {
      "search": "Christmas music",
      "terms": ["Christmas music"],
      "uri": "http://id.loc.gov/authorities/genreForms/gf2014026716"
    }
  ],
  "folgerRelatedItems" : [
    {"@id" : "", "folgerRemoteIdentification" : { "folgerRemoteUniqueID" : "http://dapdev.dev/var/folger/storage/trecento/AKG_L_Act_1.wav", "folgerRemoteSystemID" : "binary-files" }, "folgerRelationshipType" : "included audio", "folgerObjectType" : "audio", "label" : "AKG L Act 1", "mpso" : 1, "description" : "AKG L Act 1 in WAV format" },
    {"@id" : "", "folgerRemoteIdentification" : { "folgerRemoteUniqueID" : "http://dapdev.dev/var/folger/storage/trecento/AKG_L_Act_2.wav", "folgerRemoteSystemID" : "binary-files" }, "folgerRelationshipType" : "included audio", "folgerObjectType" : "audio", "label" : "AKG L Act 2", "mpso" : 2, "description" : "AKG L Act 2 in WAV format" },
    {"@id" : "", "folgerRemoteIdentification" : { "folgerRemoteUniqueID" : "http://dapdev.dev/var/folger/storage/trecento/AKG_R_Act_1.wav", "folgerRemoteSystemID" : "binary-files" }, "folgerRelationshipType" : "included audio", "folgerObjectType" : "audio", "label" : "AKG R Act 1", "mpso" : 3, "description" : "AKG R Act 1 in WAV format" },
    {"@id" : "", "folgerRemoteIdentification" : { "folgerRemoteUniqueID" : "http://dapdev.dev/var/folger/storage/trecento/AKG_R_Act_2.wav", "folgerRemoteSystemID" : "binary-files" }, "folgerRelationshipType" : "included audio", "folgerObjectType" : "audio", "label" : "AKG R Act 2", "mpso" : 1, "description" : "AKG R Act 2 in WAV format" }
  ]


}]

=== ParsonsTKO/FolgerMirandaServer/web/sample-data/json-files/video-example-taming-shrew-1908.json
[{
  "RemoteUniqueID": "http://hamnet.folger.edu/cgi-bin/Pwebrecon.cgi?BBID=126058",
  "isBasedOn": "http://hamnet.folger.edu/cgi-bin/Pwebrecon.cgi?BBID=126058",
  "name":  "Taming of the shrew (Motion Picture: 1908)" ,
  "datePublished": {"startDate": 1908, "endDate":1908},
  "dateCreated": "1908",
  "locationCreated" : 
  {
    "@type": "Place",
    "addressLocality": "Washington D.C.",
    "addressCountry": "United States",
    "URI":"http://id.loc.gov/authorities/names/n79018774"
  },
  "description": "1 videodisc (11 min.) : sd., black & white ; 4 3/4 in. Notes:  Originally released by American Mutoscope and Biograph, 1908. Released by Kino International as a supplement to their Othello (c1922). Cast list provided by Internet movie data base, 10 July 2003. DVD; Dolby digital stereo. Silent film with English intertitles.",
  "format" : "video",
  "inLanguage": "eng",
  
  "folgerRelatedItems" : [
    {"@id" : "", "folgerRemoteIdentification" : { "folgerRemoteUniqueID" : "http://dapdev.dev/var/folger/storage/shrew/Taming_of_the_Shrew_ClipDVD10.m4v", "folgerRemoteSystemID" : "binary-files" }, "folgerRelationshipType" : "included video", "folgerObjectType" : "video", "label" : "m4v of the film", "mpso" : 1, "description" : "m4v of Taming of the Shrew (1908)" }
  ]


}]

=== ParsonsTKO/FolgerMirandaServer/web/sample-data/json-files/binary-assets/binary-sample.json
[{
  "RemoteUniqueID": "http://www.dynaexamples.com/examples-manual/ls-dyna_example.zip/view",
  "fileURL": "http://www.dynaexamples.com/examples-manual/ls-dyna_example.zip/view",
  "name":  "Sample Binary File" ,
  "datePublished": {"startDate": 2017},
  "dateCreated": "2017",
  "description": "Sample Binary file: A ZIP file of LS-DYNA examples",
  "format" : "binary",
  "inLanguage": "eng",
  "publisher" : "Livermore Software Technology Corporation",  
  "contentSize" : "912k"

}]
