=== ParsonsTKO/FolgerMirandaServer/src/DAPImportBundle/Resources/schemas/luna.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {},
    "id": "contenttype/images",
    "title": "Folger Images Luna",
    "description": "",
    "items": {
        "id": "/items",
        "properties": {
            "author": {
                "id": "/items/properties/author",
                "type": "string"
            },
            "bibId": {
                "id": "/items/properties/bibId",
                "type": "integer"
            },
            "callNumber": {
                "id": "/items/properties/callNumber",
                "type": "string"
            },
            "dateCreated": {
                "id": "/items/properties/dateCreated",
                "type": "string"
            },
            "dateUpdated": {
                "id": "/items/properties/dateUpdated",
                "type": "string"
            },
            "holdingsId": {
                "id": "/items/properties/holdingsId",
                "type": "integer"
            },
            "imprintOrigin": {
                "id": "/items/properties/imprintOrigin",
                "type": "string"
            },
            "lunaImageId": {
                "id": "/items/properties/lunaImageId",
                "type": "integer"
            },
            "lunaObjectId": {
                "id": "/items/properties/lunaObjectId",
                "type": "integer"
            },
            "lunaURL": {
                "id": "/items/properties/lunaURL",
                "type": "string"
            },
            "multiPageSortOrder": {
                "id": "/items/properties/multiPageSortOrder",
                "type": "integer"
            },
            "pageNumber": {
                "id": "/items/properties/pageNumber",
                "type": "string"
            },
            "rootfile": {
                "id": "/items/properties/rootfile",
                "type": "integer"
            },
            "size4jpgURL": {
                "id": "/items/properties/size4jpgURL",
                "type": "string"
            },
            "size5jpgURL": {
                "id": "/items/properties/size5jpgURL",
                "type": "string"
            },
            "size6jpgURL": {
                "id": "/items/properties/size6jpgURL",
                "type": "string"
            },
            "size7jpgURL": {
                "id": "/items/properties/size7jpgURL",
                "type": "string"
            },
            "title": {
                "id": "/items/properties/title",
                "type": "string"
            }
        },
        "required": [
            "rootfile", "callNumber", "pageNumber", "multiPageSortOrder", "title", "author", "imprintOrigin", "bibId", "holdingsId", "lunaObjectId", "lunaImageId", "lunaURL", "size4jpgURL", "size5jpgURL", "size6jpgURL", "size7jpgURL", "dateCreated", "dateUpdated"
        ],
        "type": "object"
    },
    "type": "array"
}

=== ParsonsTKO/FolgerMirandaServer/web/sample-data/json-files/game-at-chess-luna/game-at-chess.part1-A-2.json
[
  {
    "rootfile": 143942,
    "callNumber": "STC 17884 copy 1",
    "pageNumber": "leaf A1 verso || leaf A2 recto",
    "multiPageSortOrder": 6,
    "title": "A game at chesse as it hath bine sundrey times acted at the Globe on the Banck side",
    "author": "Middleton, Thomas, d. 1627.",
    "imprintOrigin": "[1625?]",
    "bibId": 164514,
    "holdingsId": 158342,
    "lunaObjectId": 210663,
    "lunaImageId": 1214957,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~1214957~210663",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1~6~6/647/143942.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143942.jp2&level=2&width=1677&height=1104",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143942.jp2&level=1&width=3354&height=2209",
    "size7jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143942.jp2&width=6709&height=4420",
    "dateCreated": "2016-12-06T16:36:24Z",
    "dateUpdated": "2016-12-06T16:36:24Z"
  },
  {
    "rootfile": 143943,
    "callNumber": "STC 17884 copy 1",
    "pageNumber": "leaf A2 verso || leaf A3 recto (page 1)",
    "multiPageSortOrder": 7,
    "title": "A game at chesse as it hath bine sundrey times acted at the Globe on the Banck side",
    "author": "Middleton, Thomas, d. 1627.",
    "imprintOrigin": "[1625?]",
    "bibId": 164514,
    "holdingsId": 158342,
    "lunaObjectId": 210662,
    "lunaImageId": 1214958,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~1214958~210662",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1~6~6/647/143943.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143943.jp2&level=2&width=1681&height=1102",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143943.jp2&level=1&width=3363&height=2206",
    "size7jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143943.jp2&width=6727&height=4413",
    "dateCreated": "2016-12-06T16:36:24Z",
    "dateUpdated": "2016-12-06T16:36:24Z"
  },
  {
    "rootfile": 143944,
    "callNumber": "STC 17884 copy 1",
    "pageNumber": "leaf A3 verso (page 2) || leaf A4 recto (page 3)",
    "multiPageSortOrder": 8,
    "title": "A game at chesse as it hath bine sundrey times acted at the Globe on the Banck side",
    "author": "Middleton, Thomas, d. 1627.",
    "imprintOrigin": "[1625?]",
    "bibId": 164514,
    "holdingsId": 158342,
    "lunaObjectId": 210661,
    "lunaImageId": 1214959,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~1214959~210661",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1~6~6/647/143944.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143944.jp2&level=2&width=1677&height=1100",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143944.jp2&level=1&width=3354&height=2201",
    "size7jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143944.jp2&width=6709&height=4404",
    "dateCreated": "2016-12-06T16:36:24Z",
    "dateUpdated": "2016-12-06T16:36:24Z"
  },
  {
    "rootfile": 143945,
    "callNumber": "STC 17884 copy 1",
    "pageNumber": "leaf A4 verso (page 4) || leaf B1 recto (page 5)",
    "multiPageSortOrder": 9,
    "title": "A game at chesse as it hath bine sundrey times acted at the Globe on the Banck side",
    "author": "Middleton, Thomas, d. 1627.",
    "imprintOrigin": "[1625?]",
    "bibId": 164514,
    "holdingsId": 158342,
    "lunaObjectId": 210660,
    "lunaImageId": 1214960,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~1214960~210660",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1~6~6/647/143945.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143945.jp2&level=2&width=1674&height=1099",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143945.jp2&level=1&width=3349&height=2200",
    "size7jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143945.jp2&width=6698&height=4400",
    "dateCreated": "2016-12-06T16:36:24Z",
    "dateUpdated": "2016-12-06T16:36:25Z"
  },
  {
    "rootfile": 143946,
    "callNumber": "STC 17884 copy 1",
    "pageNumber": "leaf B1 verso (page 6) || leaf B2 recto (page 7)",
    "multiPageSortOrder": 10,
    "title": "A game at chesse as it hath bine sundrey times acted at the Globe on the Banck side",
    "author": "Middleton, Thomas, d. 1627.",
    "imprintOrigin": "[1625?]",
    "bibId": 164514,
    "holdingsId": 158342,
    "lunaObjectId": 210659,
    "lunaImageId": 1214961,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~1214961~210659",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1~6~6/647/143946.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143946.jp2&level=2&width=1664&height=1093",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143946.jp2&level=1&width=3328&height=2186",
    "size7jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143946.jp2&width=6656&height=4372",
    "dateCreated": "2016-12-06T16:36:25Z",
    "dateUpdated": "2016-12-06T16:36:25Z"
  },
  {
    "rootfile": 143947,
    "callNumber": "STC 17884 copy 1",
    "pageNumber": "leaf B2 verso (page 8) || leaf B3 recto (page 9)",
    "multiPageSortOrder": 11,
    "title": "A game at chesse as it hath bine sundrey times acted at the Globe on the Banck side",
    "author": "Middleton, Thomas, d. 1627.",
    "imprintOrigin": "[1625?]",
    "bibId": 164514,
    "holdingsId": 158342,
    "lunaObjectId": 210658,
    "lunaImageId": 1214962,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~1214962~210658",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1~6~6/647/143947.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143947.jp2&level=2&width=1674&height=1096",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143947.jp2&level=1&width=3349&height=2193",
    "size7jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143947.jp2&width=6698&height=4386",
    "dateCreated": "2016-12-06T16:36:25Z",
    "dateUpdated": "2016-12-06T16:36:25Z"
  }
]

=== ParsonsTKO/FolgerMirandaServer/src/DAPImportBundle/Resources/examples/luna_small_gac_example.json
[
  {
    "rootfile": 143937,
    "callNumber": "STC 17884 copy 1",
    "pageNumber": "front outside cover",
    "multiPageSortOrder": 1,
    "title": "A game at chesse as it hath bine sundrey times acted at the Globe on the Banck side",
    "author": "Middleton, Thomas, d. 1627.",
    "imprintOrigin": "[1625?]",
    "bibId": 164514,
    "holdingsId": 158342,
    "lunaObjectId": 210668,
    "lunaImageId": 1214952,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~1214952~210668",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1~6~6/647/143937.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143937.jp2&level=2&width=1238&height=1568",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143937.jp2&level=1&width=2478&height=3137",
    "size7jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143937.jp2&width=4957&height=6274",
    "dateCreated": "2016-12-06T16:36:24Z",
    "dateUpdated": "2016-12-06T16:36:24Z"
  }
]

=== ParsonsTKO/FolgerMirandaServer/web/sample-data/json-files/game-at-chess-luna/game-at-chess.part1-A.json
[
  {
    "rootfile": 143937,
    "callNumber": "STC 17884 copy 1",
    "pageNumber": "front outside cover",
    "multiPageSortOrder": 1,
    "title": "A game at chesse as it hath bine sundrey times acted at the Globe on the Banck side",
    "author": "Middleton, Thomas, d. 1627.",
    "imprintOrigin": "[1625?]",
    "bibId": 164514,
    "holdingsId": 158342,
    "lunaObjectId": 210668,
    "lunaImageId": 1214952,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~1214952~210668",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1~6~6/647/143937.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143937.jp2&level=2&width=1238&height=1568",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143937.jp2&level=1&width=2478&height=3137",
    "size7jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143937.jp2&width=4957&height=6274",
    "dateCreated": "2016-12-06T16:36:24Z",
    "dateUpdated": "2016-12-06T16:36:24Z"
  },
  {
    "rootfile": 143938,
    "callNumber": "STC 17884 copy 1",
    "pageNumber": "front inside cover || front endleaf 1 recto",
    "multiPageSortOrder": 2,
    "title": "A game at chesse as it hath bine sundrey times acted at the Globe on the Banck side",
    "author": "Middleton, Thomas, d. 1627.",
    "imprintOrigin": "[1625?]",
    "bibId": 164514,
    "holdingsId": 158342,
    "lunaObjectId": 210667,
    "lunaImageId": 1214953,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~1214953~210667",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1~6~6/647/143938.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143938.jp2&level=2&width=1679&height=1115",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143938.jp2&level=1&width=3359&height=2232",
    "size7jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143938.jp2&width=6718&height=4465",
    "dateCreated": "2016-12-06T16:36:24Z",
    "dateUpdated": "2016-12-06T16:36:24Z"
  },
  {
    "rootfile": 143939,
    "callNumber": "STC 17884 copy 1",
    "pageNumber": "front endleaf 1 verso || front endleaf 2 recto",
    "multiPageSortOrder": 3,
    "title": "A game at chesse as it hath bine sundrey times acted at the Globe on the Banck side",
    "author": "Middleton, Thomas, d. 1627.",
    "imprintOrigin": "[1625?]",
    "bibId": 164514,
    "holdingsId": 158342,
    "lunaObjectId": 210666,
    "lunaImageId": 1214954,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~1214954~210666",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1~6~6/647/143939.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143939.jp2&level=2&width=1673&height=1112",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143939.jp2&level=1&width=3346&height=2225",
    "size7jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143939.jp2&width=6693&height=4452",
    "dateCreated": "2016-12-06T16:36:24Z",
    "dateUpdated": "2016-12-06T16:36:24Z"
  },
  {
    "rootfile": 14394,
    "callNumber": "STC 22313 copy 2",
    "pageNumber": "front endleaf 2v || front endleaf 3r",
    "multiPageSortOrder": 4,
    "title": "[King Richard II] The life and death of King Richard the second. With new additions of the Parliament scene, and the deposing of King Richard.",
    "author": "Shakespeare, William, 1564-1616.",
    "imprintOrigin": "1634",
    "bibId": 163923,
    "holdingsId": 157499,
    "lunaObjectId": 108701,
    "lunaImageId": 141640,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~141640~108701",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1-6-NA/1072/014394.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1-6-NA/1072/014394.jp2&level=2&width=1767&height=1256",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1-6-NA/1072/014394.jp2&level=1&width=3534&height=2512",
    "size7jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1-6-NA/1072/014394.jp2&width=7068&height=5025",
    "dateCreated": "2014-12-30T17:31:14Z",
    "dateUpdated": "2014-12-30T17:31:14Z"
  },
  {
    "rootfile": 143940,
    "callNumber": "STC 17884 copy 1",
    "pageNumber": "front endleaf 2 verso || front endleaf 3 recto",
    "multiPageSortOrder": 4,
    "title": "A game at chesse as it hath bine sundrey times acted at the Globe on the Banck side",
    "author": "Middleton, Thomas, d. 1627.",
    "imprintOrigin": "[1625?]",
    "bibId": 164514,
    "holdingsId": 158342,
    "lunaObjectId": 210665,
    "lunaImageId": 1214955,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~1214955~210665",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1~6~6/647/143940.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143940.jp2&level=2&width=1681&height=1112",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143940.jp2&level=1&width=3362&height=2225",
    "size7jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143940.jp2&width=6725&height=4452",
    "dateCreated": "2016-12-06T16:36:24Z",
    "dateUpdated": "2016-12-06T16:36:24Z"
  },
  {
    "rootfile": 143941,
    "callNumber": "STC 17884 copy 1",
    "pageNumber": "front endleaf 3 verso || leaf A1 recto",
    "multiPageSortOrder": 5,
    "title": "A game at chesse as it hath bine sundrey times acted at the Globe on the Banck side",
    "author": "Middleton, Thomas, d. 1627.",
    "imprintOrigin": "[1625?]",
    "bibId": 164514,
    "holdingsId": 158342,
    "lunaObjectId": 210664,
    "lunaImageId": 1214956,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~1214956~210664",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1~6~6/647/143941.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143941.jp2&level=2&width=1665&height=1100",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143941.jp2&level=1&width=3330&height=2201",
    "size7jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1~6~6/647/143941.jp2&width=6661&height=4404",
    "dateCreated": "2016-12-06T16:36:24Z",
    "dateUpdated": "2016-12-06T16:36:24Z"
  }
]

=== ParsonsTKO/FolgerMirandaServer/src/DAPImportBundle/Resources/examples/luna_example.json
[
  {
    "rootfile": 38759,
    "callNumber": "L.a.1",
    "pageNumber": "leaf 1 recto",
    "multiPageSortOrder": 1,
    "title": "Letter from Humphrey Adderley, Lincoln's Inn, to Walter Bagot",
    "author": "",
    "imprintOrigin": "1620 May 24",
    "bibId": 230544,
    "holdingsId": 310297,
    "lunaObjectId": 129775,
    "lunaImageId": 353152,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~353152~129775",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1-6-NA/1168/038759.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1-6-NA/1168/038759.jp2&level=2&width=2150&height=3051",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1-6-NA/1168/038759.jp2&level=1&width=4301&height=6102",
    "size7jpgURL": "",
    "dateCreated": "2014-12-30T17:03:54Z",
    "dateUpdated": "2016-12-06T15:27:13Z"
  },
  {
    "rootfile": 38760,
    "callNumber": "L.a.1",
    "pageNumber": "leaf 1 verso || leaf 2 recto",
    "multiPageSortOrder": 2,
    "title": "Letter from Humphrey Adderley, Lincoln's Inn, to Walter Bagot",
    "author": "",
    "imprintOrigin": "1620 May 24",
    "bibId": 230544,
    "holdingsId": 310297,
    "lunaObjectId": 129776,
    "lunaImageId": 353161,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~353161~129776",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1-6-NA/1168/038760.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1-6-NA/1168/038760.jp2&level=2&width=1541&height=1110",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1-6-NA/1168/038760.jp2&level=1&width=3082&height=2221",
    "size7jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1-6-NA/1168/038760.jp2&width=6165&height=4443",
    "dateCreated": "2014-12-30T17:03:55Z",
    "dateUpdated": "2016-12-06T15:27:15Z"
  },
  {
    "rootfile": 38761,
    "callNumber": "L.a.1",
    "pageNumber": "leaf 2 verso",
    "multiPageSortOrder": 3,
    "title": "Letter from Humphrey Adderley, Lincoln's Inn, to Walter Bagot",
    "author": "",
    "imprintOrigin": "1620 May 24",
    "bibId": 230544,
    "holdingsId": 310297,
    "lunaObjectId": 129777,
    "lunaImageId": 353170,
    "lunaURL": "http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~353170~129777",
    "size4jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/Size4/FOLGERCM1-6-NA/1168/038761.jpg",
    "size5jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1-6-NA/1168/038761.jp2&level=2&width=2151&height=3051",
    "size6jpgURL": "http://luna.folger.edu:80/MediaManager/srvr?mediafile=/JP2K/FOLGERCM1-6-NA/1168/038761.jp2&level=1&width=4302&height=6102",
    "size7jpgURL": "",
    "dateCreated": "2014-12-30T17:03:55Z",
    "dateUpdated": "2016-12-06T15:27:16Z"
  }
]
